[박현우] Mission 2 : 모델링
wecode-bootcamp-korea/25-westagram-backend pull request #11
Opened 2021-09-16 11:15 UTC by Pagnim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-17 01:45 UTC, lordmyshepherd requested changes

2021-09-17 01:45 UTC, lordmyshepherd commented on students/hyeon_woo/westagram/users/models.py
> +
빈 줄은 지워주세요~

2021-09-17 01:45 UTC, lordmyshepherd commented on students/hyeon_woo/westagram/users/models.py
> +    information   = models.CharField(max_length=255)
email field에 `unique` 속성을 추가하셔서 유저가 중복 저장되는 문제가 발생하지 않도록 수정해주세요!
unique 속성을 어떻게 적용하는지는 공식 문서에서 찾아보세요~

2021-09-17 01:45 UTC, lordmyshepherd commented on students/hyeon_woo/westagram/users/models.py
> +    password      = models.CharField(max_length=50)
password는 추후에 암호화해서 저장해야 하기 때문에 넉넉하게 `max_length=200`으로 수정해주세요~

2021-09-17 01:50 UTC, lordmyshepherd commented on students/hyeon_woo/westagram/users/models.py
> +
데이터의 이력 관리를 위해서 `created_at`, `updated_at` column을 추가해주세요. 
```python 
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 
```

2021-09-17 05:22 UTC, Pagnim commented on students/hyeon_woo/westagram/users/models.py
> +
수정했습니다!

2021-09-17 05:22 UTC, Pagnim commented on students/hyeon_woo/westagram/users/models.py
> +    information   = models.CharField(max_length=255)
추가했습니다!

2021-09-17 05:22 UTC, Pagnim commented on students/hyeon_woo/westagram/users/models.py
> +    password      = models.CharField(max_length=50)
200으로 바꿨습니다!

2021-09-17 05:22 UTC, Pagnim commented on students/hyeon_woo/westagram/users/models.py
> +
추가했습니다

2021-09-18 09:41 UTC, lordmyshepherd requested changes

2021-09-18 09:41 UTC, lordmyshepherd commented on students/hyeon_woo/westagram/users/views.py
> +import re
불필요한 import문은 지워주시고, import문 순서를 잘 지켜서 만들어주세요.
(python convention 문서 참고해주세요.)

```python
# 파이썬 built-in 모듈
import json
import re

# 외부 모듈
from django.http      import JsonResponse
from django.views     import View

# 내가 만든 사용자 모듈
from users.models     import User
```

2021-09-18 09:41 UTC, lordmyshepherd commented on students/hyeon_woo/westagram/users/views.py
> +
```suggestion

REGEX_EMAIL = r"^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"
REGEX_PASSWORD = ..

class SignUpView(View):
    def post(self,request):
        data = json.loads(request.body)
        try:
            if User.objects.filter(email=data['email']).exists():
                return JsonResponse({"message": "Please use a different email"}, status=400)
            if (data["password"] == ""):
                return JsonResponse({"message": "Please enter a password"}, status=400)
            if (data["email"] == ""):
                return JsonResponse({"message": "Please enter a email"}, status=400)
                
            if not re.match(REGEX_EMAIL, data["email"]):
                return JsonResponse({"message": "Email_Error : Need @ and ."}, status=400)
                
            if len(data["password"]) < 8 :
                return JsonResponse({"message": "Password must be at least 8 characters in length"}, status=400)
```

2021-09-28 02:22 UTC, Pagnim commented on students/hyeon_woo/westagram/users/views.py
> +import re
수정했습니다

2021-09-28 02:29 UTC, Pagnim commented on students/hyeon_woo/westagram/users/views.py
> +
수정했습니다!

2021-09-28 05:55 UTC, kyeongraekim requested changes
현우님 아래 내용 보고 참고해서 수정해주세요~

2021-09-28 05:55 UTC, kyeongraekim commented on students/hyeon_woo/westagram/users/views.py
> +                return JsonResponse({"message": "Please enter a email"}, status=400)
현재 작성해주신 모델과 비교하여서, data['password'] 와 data['email'] 로 값을 불러 올 때 null값이나 빈 스트링이 들어올 수 없습니다.  
null=True or False /// blank=True or False 이 두가지 속성값을 지닌 모델과, 현재 작성해주신 View 파일 내 코드사이의 상관관계를 잘 따져보시고 해당 코드를 남길지 지울지 판단해주세요!

2021-09-28 05:55 UTC, kyeongraekim commented on students/hyeon_woo/westagram/users/views.py
> +                return JsonResponse({"message": "Password_Error : Need LETTER,NUMBER,SPECIAL_SYMBOLS"}, status=400)
패스워드의 최소길이가 정규표현식에서 설정이 되어있지 않은 것 같은데 확인 부탁드려요~

2021-09-28 05:55 UTC, kyeongraekim commented on students/hyeon_woo/westagram/users/views.py
> +            if len(data["password"]) < 8 :
정규표현식에서의 최소 길이 설정으로 변경해주세요.

2021-09-28 05:55 UTC, kyeongraekim commented on students/hyeon_woo/westagram/users/views.py
> +
try 이후의 줄바꿈 공백이 불필요해 보입니다. 삭제해주세요.

2021-09-28 06:35 UTC, Pagnim commented on students/hyeon_woo/westagram/users/views.py
> +                return JsonResponse({"message": "Password_Error : Need LETTER,NUMBER,SPECIAL_SYMBOLS"}, status=400)
아래 if문과 합쳤습니다

2021-09-28 06:35 UTC, Pagnim commented on students/hyeon_woo/westagram/users/views.py
> +            if len(data["password"]) < 8 :
정규표현식과 합쳤습니다

2021-09-28 06:35 UTC, Pagnim commented on students/hyeon_woo/westagram/users/views.py
> +
삭제 완료했습니다!

2021-09-28 06:44 UTC, Pagnim commented on students/hyeon_woo/westagram/users/views.py
> +                return JsonResponse({"message": "Please enter a email"}, status=400)
null, blank는 디폴트 값이 false이고 아래의 정규표현식에의 조건에서 이미 빈 값을 걸러주는 요소가 포함되어 있어서 삭제하였습니다!

2021-09-28 07:36 UTC, lordmyshepherd commented
LGTM 👍

2021-09-28 07:36 UTC, merged