[이다빈] Mission 2 : 모델링
wecode-bootcamp-korea/25-westagram-backend pull request #12
Opened 2021-09-16 11:39 UTC by thisisempty

created user model

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- westagram users 모델 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- users 모델 : 이름, 이메일, 비밀번호, 연락처(휴대폰), 그 외 개인정보(웹사이트, 소개)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- database column에 바로 unique 제약조건을 걸어도 될까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-17 01:49 UTC, lordmyshepherd requested changes

2021-09-17 01:49 UTC, lordmyshepherd commented on students/dabeen/westagram/users/models.py
> +    email = models.CharField(max_length=45, unique=True)
`unique=True` 속성 👍

2021-09-17 01:49 UTC, lordmyshepherd commented on students/dabeen/westagram/users/models.py
> +    password = models.CharField(max_length=45)
password는 추후에 암호화해서 저장해야 하기 때문에 넉넉하게 max_length=200으로 수정해주세요~

2021-09-17 01:49 UTC, lordmyshepherd commented on students/dabeen/westagram/users/models.py
> +    information = models.TextField(null=True)
데이터의 이력 관리를 위해서 `created_at`, `updated_at` column을 추가해주세요~
```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2021-09-17 02:30 UTC, thisisempty commented on students/dabeen/westagram/users/models.py
> +    password = models.CharField(max_length=45)
수정했습니다!

2021-09-17 02:31 UTC, thisisempty commented on students/dabeen/westagram/users/models.py
> +    information = models.TextField(null=True)
추가했습니다!

2021-09-18 09:18 UTC, lordmyshepherd commented
LGTM 👍

2021-09-18 09:19 UTC, merged