[김민호] Mission 2: 모델링
wecode-bootcamp-korea/25-westagram-backend pull request #21
Opened 2021-09-17 07:43 UTC by maxkmh712

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-18 09:43 UTC, lordmyshepherd requested changes

2021-09-18 09:43 UTC, lordmyshepherd commented on students/minho/users/models.py
> +    email           = models.CharField(max_length=45, unique=True)
`unique=True` 속성 주셨네요! 👍

2021-09-18 09:43 UTC, lordmyshepherd commented on students/minho/users/models.py
> +    password        = models.CharField(max_length=45)
password는 추후에 암호화해서 저장해야 하기 때문에 넉넉하게 max_length=200으로 수정해주세요~

2021-09-18 09:43 UTC, lordmyshepherd commented on students/minho/users/models.py
> +    other_info      = models.CharField(max_length=300, null=True)
데이터의 이력 관리를 위해서 `created_at`, `updated_at` column을 추가해주세요. 
```python 
created_at = models.DateTimeField(auto_now_add=True) 
updated_at = models.DateTimeField(auto_now=True) 
```

2021-09-19 00:35 UTC, maxkmh712 commented on students/minho/users/models.py
> +    password        = models.CharField(max_length=45)
수정했습니다!

2021-09-19 00:36 UTC, maxkmh712 commented on students/minho/users/models.py
> +    other_info      = models.CharField(max_length=300, null=True)
추가했습니다!

2021-09-27 02:24 UTC, kyeongraekim commented
수정 확인했습니다 민호님  LGTM!~

2021-09-27 02:36 UTC, kyeongraekim commented on students/minho/users/models.py
> +    password        = models.CharField(max_length=45)
수정 확인했습니다~

2021-09-27 02:36 UTC, kyeongraekim commented on students/minho/users/models.py
> +    other_info      = models.CharField(max_length=300, null=True)
수정 확인했습니다~

2021-09-27 02:37 UTC, kyeongraekim requested changes
민호님~ 리뷰 수정 반영 잘 해주셨네요.
딱 한가지, 사항으로 변수명 이후의 '=' 작성 시 스페이스 공백은 가장 긴 변수명을 기준으로 한 칸이면 충분합니다.

2021-09-28 01:05 UTC, kyeongraekim commented
Git Closing 사유: 민호님 깃 꼬임으로 인해 처음부터 새롭게 다시 작성해서 PR을 올리심.

2021-09-28 01:06 UTC, closed without merging