ADD: users modeling
wecode-bootcamp-korea/25-westagram-backend pull request #22
Opened 2021-09-18 13:25 UTC by qhsdnr0

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Models.py User class 작성완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- name, email, password, phone_number, date_of_birth, created_at, updated_at 필드 추가
- shell을 통해 데이터베이스에 데이터 저장 확인

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 특이사항 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-27 03:05 UTC, kyeongraekim requested changes
안녕하세요 본욱님 리뷰사항 확인해주시고 수정 반영해주세요~

2021-09-27 03:05 UTC, kyeongraekim commented on students/bonwook/westagram/users/models.py
> +    date_of_birth   = models.DateField()
DateField()의 default 값이 무엇인지 확인해주세요. 그리고 인별그램 기획상 가입 시 생년월일이 필 수 기입 사항일지 말지 확인해주세요~

2021-09-27 03:05 UTC, kyeongraekim commented on students/bonwook/westagram/users/models.py
> +        max_length  = 200,
더 많은 값이 들어 가야 한다면 줄나눔이 필요시되보이지만, 필드 값 속성이 세 개 정도면 한 줄로 작성해도 무방할 것 같아요.
하지만 제 3자의 가독성을 위해 이렇게 선고려해주시고 나눠 주신 점은 잘해주셨습니다!

2021-09-27 04:12 UTC, qhsdnr0 commented on students/bonwook/westagram/users/models.py
> +        max_length  = 200,
우선 리뷰 감사드립니다 :)
제 화면 기준에선 속성이 3개만 되어도 화면을 넘어가버리는 바람에 보기가 불편하다고 생각해서 줄바꿈 적용했습니다.
문제가 되지않는다면 이대로 두어도 괜찮을까요??

2021-09-27 04:20 UTC, qhsdnr0 commented on students/bonwook/westagram/users/models.py
> +    date_of_birth   = models.DateField()
리뷰 감사드립니다 :)
생년월일을 선택으로 주려고 했는데 추가 옵션 입력을 고려하지 않아서 필수입력사항으로 지정됐습니다..
수정 후 다시 올리도록 하겠습니다.

2021-09-27 09:09 UTC, lordmyshepherd commented on students/bonwook/westagram/users/models.py
> +        max_length  = 200,
80칸 까지는 줄바꿈하지 않는 것이 원칙입니다. 컨벤션이 있는 이유는 동료들이 같은 코드 스타일을 사용하기 위함이니 수정해주세요~
다만 80칸이 넘어간다면 작성하신 방법이 가독성을 높이는 방법이겠습니다.

2021-09-27 09:33 UTC, qhsdnr0 commented on students/bonwook/westagram/users/models.py
> +        max_length  = 200,
네 수정완료했습니다

2021-09-28 01:22 UTC, kyeongraekim approved these changes

2021-09-28 01:22 UTC, kyeongraekim commented
LGTM!~ 작성해주신 다음 내용 차례로 PR 올려주세요!
그 과정에서 깃 컨플릭트가 생긴다면 꼭 해결하고 올려주세요~

2021-09-28 01:22 UTC, merged