[김민찬] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/25-westagram-backend pull request #28
Opened 2021-09-22 09:31 UTC by cozyClassic

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 기능 간단 구현
		 
## 수정 사항들 자세한 내용
- 이메일, 패스워드로 로그인
- post로 로그인 요청
- 검사항목1. post 값에 "email", "password"가 존재 하는지 여부.
- 검사항목2. 들어온 "email" 값이 데이터베이스에 존재하는지 여부
- 검사항목3. 들어온 email, password가 데이터에 있는 값과 일치하는지 여부
- 추가 수정사항1 : 유저 회원가입 기능에서, elif로 되어 있던 검사항목을 if 로 수정.
- 추가 수정사항2 : 유저 회원가입 기능에서, 필터에 걸려서 status=400으로 반환하던 항목을 status=401로 수정.

## 기타 질문 및 특이 사항
쿼리셋에 있는 데이터가 있는지 여부를 표현하는 방법에 len==0 이나
if Users.objects.get() 으로 표현하는 것 말고 또 있을까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-27 06:59 UTC, lordmyshepherd requested changes

2021-09-27 06:59 UTC, lordmyshepherd commented on students/minchan/westagram/users/views.py
> +        return HttpResponse("HI")
해당 코드는 이전 PR에 있는 코드이므로 이번 로그인 기능 PR에서는 삭제해주시고, 로그인 관련된 코드만 올라올 수 있도록 수정해주세요.

하나의 PR당 하나의 기능만 올리는 습관을 만들어주세요.
```suggestion
```

2021-09-27 06:59 UTC, lordmyshepherd commented on students/minchan/westagram/users/views.py
> +class user_login(View) :
위에 `UserView` Class에 합쳐주세요~ Class형 View를 사용하는 이유입니다.

```suggestion
class user_login(View) :
```

2021-09-27 09:59 UTC, cozyClassic commented on students/minchan/westagram/users/views.py
> +        return HttpResponse("HI")
죄송하지만 마지막에 커밋한 파일만 읽어주세요!

2021-09-27 10:00 UTC, cozyClassic commented on students/minchan/westagram/users/views.py
> +class user_login(View) :
클래스명 CamelCase로 변경하고, get함수는 아예 삭제해버렸습니다.

2021-09-28 02:00 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-28 02:00 UTC, merged