[이기용] Mission 1 : Django 초기 세팅
wecode-bootcamp-korea/25-westagram-backend pull request #30
Opened 2021-09-23 14:45 UTC by leeky940926

명절동안 초기세팅부터 대댓글까지 한 번 돌려봤습니다.
최초세팅부터 다시 돌려보며, 부족한 부분이 어딘지 놓친 부분이 있는지 체크하는 시간이 되었습니다.

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-27 05:56 UTC, kyeongraekim requested changes
리뷰 내용 확인해주시고 수정해주세요~

2021-09-27 05:56 UTC, kyeongraekim commented on students/kylee/westagram/urls.py
> +from django.contrib import admin
사용하지 않는 import 문은 제거해주세요.

2021-09-27 05:56 UTC, kyeongraekim commented on students/kylee/westagram/settings.py
> +
중간에 append_slash = False 부분이 빠져있네요. 어떠한 기능을 하는지 한 번 리서치해보세요!

2021-09-27 06:11 UTC, leeky940926 commented on students/kylee/westagram/urls.py
> +from django.contrib import admin
제거하고 다시 커밋하여 올렸습니다!

2021-09-27 06:12 UTC, leeky940926 commented on students/kylee/westagram/settings.py
> +
urls.py에서 url 관련하여 설정해준다는 걸 알게 되었습니다.

추가 후 커밋했습니다!

2021-09-28 01:13 UTC, kyeongraekim approved these changes

2021-09-28 01:14 UTC, merged

2021-09-28 01:14 UTC, kyeongraekim commented
LGTM! 다음 단계 작성해주신 내용 PR들 차례대로 진행해주세요~