[박치훈] Mission 3 : 회원가입 기능 구현
wecode-bootcamp-korea/25-westagram-backend pull request #35
Opened 2021-09-26 08:29 UTC by chihunmanse

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일, 비밀번호 정규표현식으로 검사, 실패시 에러 반환
- 이메일 중복시 에러 반환
- KeyError시 에러 반환
- JSONDecodeError시 에러 반환
- 성공시 201 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-27 08:46 UTC, lordmyshepherd requested changes

2021-09-27 08:46 UTC, lordmyshepherd commented on students/chihun/users/views.py
> +                return JsonResponse({'MESSAGE':'ALREADY_EXISTS_EMAIL'}, status=400)
매칭되는 자원(record)이 없는 경우에는 `status code 404`를 반환합니다.

```suggestion
                return JsonResponse({'MESSAGE':'ALREADY_EXISTS_EMAIL'}, status=404)
```

2021-09-27 08:46 UTC, lordmyshepherd commented on students/chihun/users/views.py
> +            blog_url     = data.get('blog_url')  # null = True
주석 `# null = True`는 뭔가요??

2021-09-28 01:41 UTC, kyeongraekim commented
LGTM!~ 깃 컨플릭트 발생 가능성에 유의하며 진행해주신 다음 내용 차례로 PR 올려주세요 치훈님!

2021-09-28 01:42 UTC, merged