[이기용] Mission 2 : 모델링
wecode-bootcamp-korea/25-westagram-backend pull request #38
Opened 2021-09-27 06:39 UTC by leeky940926

모델링 작업입니다.
이메일이 중복되면 안되기 때문에  primary_key=True로 설정했습니다.

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-27 07:07 UTC, lordmyshepherd requested changes

2021-09-27 07:07 UTC, lordmyshepherd commented on students/kylee/users/models.py
> +    birthday = models.DateField()
1. 불필요한 주석은 지워주세요.
2. email에 unique 속성을 추가해주세요. 그렇지 않으면 사용자가 중복 저장될 수 있습니다.
3. tel -> `telephone` 변수를 줄여서 작성하지 않도록 주의해주세요.

```suggestion
class Users(models.Model) :
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50, primary_key=True)
    password = models.CharField(max_length=500)
    telephone = models.CharField(max_length=15)
    birthday = models.DateField()
```

2021-09-27 07:09 UTC, lordmyshepherd requested changes

2021-09-27 07:09 UTC, lordmyshepherd commented on students/kylee/users/models.py
> +
이력 관리를 위해서 아래 컬럼을 추가로 넣어주세요.

```python
    updated_at    = models.DateTimeField(auto_now=True)
    created_at    = models.DateTimeField(auto_now_add=True)
```

2021-09-27 07:18 UTC, leeky940926 commented on students/kylee/users/models.py
> +
수정사항 반영 후 커밋했습니다!

2021-09-27 07:19 UTC, leeky940926 commented on students/kylee/users/models.py
> +    birthday = models.DateField()
수정사항 반영 후 커밋했습니다!

2021-09-27 07:58 UTC, leeky940926 commented
병민님 pull 해도 될까요?

2021-09-27 08:39 UTC, leeky940926 commented on students/kylee/users/models.py
> +    birthday = models.DateField()
생각해보니 이메일에 unique=true를 설정하면 pk=true를 할 이유가 없다고 판단하여
primary_key=true는 지우고 unique=true만 될 수 있게 재설정해서 커밋했습니다.
확인 부탁 드립니다.

2021-09-28 05:21 UTC, kyeongraekim commented
LGTM!~

2021-09-28 05:21 UTC, merged