[김민호] Mission 2: 모델링 2차 수정 & Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/25-westagram-backend pull request #39
Opened 2021-09-27 07:42 UTC by maxkmh712

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
-models.py indent 수정
-회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-27 08:53 UTC, kyeongraekim requested changes
민호님~ 아까 라운지에서 오고 갔던 전반적인 공백 문제를 위주로 해결해주세요.

2021-09-27 08:53 UTC, kyeongraekim commented on students/minho/users/views.py
> +
 공백이 불필요해 보입니다. 삭제 부탁드려요.

2021-09-27 08:53 UTC, kyeongraekim commented on students/minho/users/views.py
> +			if User.objects.filter(email = email).exists():
전반적으로 아까 말씀하신 탭과 스페이스의 조합으로 인해 vscode에서 스페이싱 오류를 낸 것 같아요.
깃허브상 다른 코드와 비교해보니 불필요한 공백이 확연히 보입니다.
전체 공백을 다 지워보고 다시 정렬을 맞춰보세요.

2021-09-27 08:53 UTC, kyeongraekim commented on students/minho/users/views.py
> +					email 		 = email,
이곳도 변수명간 공백 불일치를 수정해주세요!

2021-09-27 10:07 UTC, maxkmh712 commented on students/minho/users/views.py
> +
넵 수정했습니다!

2021-09-27 10:09 UTC, maxkmh712 commented on students/minho/users/views.py
> +			if User.objects.filter(email = email).exists():
수정했습니다!

2021-09-27 10:09 UTC, maxkmh712 commented on students/minho/users/views.py
> +					email 		 = email,
넵 수정했습니다!

2021-09-28 01:02 UTC, kyeongraekim commented
수정 확인 했습니다~ LGTM!
단, 다음부터는 깃 실수를 최소화해서 기능별로 PR을 올릴 수 있게 해주세요 ^^

2021-09-28 01:03 UTC, kyeongraekim approved these changes

2021-09-28 01:03 UTC, merged