[김도훈] MISSION 5, 6 회원가입 비밀번호 암호화 적, 로그인 JWT 적용
wecode-bootcamp-korea/25-westagram-backend pull request #42
Opened 2021-09-27 08:51 UTC by cheesepuff90

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-27 13:47 UTC, cheesepuff90 commented
![암호화](https://user-images.githubusercontent.com/56703088/134921229-0754f29c-098f-4d9a-a750-70795d0b8205.png)
![jwt success](https://user-images.githubusercontent.com/56703088/134921235-c7dda261-21b2-492c-9461-38b204581f3f.png)

2021-09-28 02:54 UTC, kyeongraekim requested changes
도훈님~ 리뷰 내용 확인하고 반영해주세요! 어제 저녁에 같이 보았던 암호화 jwt 부분은 잘 반영해 주신 것 같네요!

2021-09-28 02:54 UTC, kyeongraekim commented on students/dohun/westagram/users/views.py
> +            decode_password = hashed_password.decode('utf-8')
- 변수명 스페이싱이 조금 아쉽네요. 재정렬 부탁드려요~
- decode 변수명도 위 처럼 명사화 해주세요~

2021-09-28 02:54 UTC, kyeongraekim commented on students/dohun/westagram/users/views.py
> +                password     = decode_password,
위 변수명이 변경되면 이 곳도 일치화가 필요할 것 같아보이네요.

2021-09-28 02:54 UTC, kyeongraekim commented on students/dohun/westagram/users/views.py
>                  etc_info     = data['etc_info']
기타 정보가 없다면 키에러가 날 코드 구조로 보이네요. data.get() 메소드를 학습해보시고 null 값이나 빈값에 대한 디폴트 값을 어떻게 줄지 한 번 고민해보세요!

2021-09-28 02:54 UTC, kyeongraekim commented on students/dohun/westagram/users/views.py
>  class UserView(View):
UserView 클래스 명이 명확치 않습니다. 회원가입 View임을 확실히 알아 볼 수 있게 변경해주세요!

2021-09-28 07:38 UTC, lordmyshepherd commented
LGTM 👍

2021-09-28 07:38 UTC, merged