[문승준] Mission 4. 로그인 기능 구현
wecode-bootcamp-korea/25-westagram-backend pull request #56
Opened 2021-09-28 08:57 UTC by palza4dev

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 기능 view 작성
		 
## 수정 사항들 자세한 내용
- email이나 password 키가 없으면 키에러 메시지 반환
- input_email이 올바르지 않으면 invalid_email 메시지 반환
- input_email의 user password와 input_password가 같으면 로그인 성공
- `/login` 으로 url 연결 완료

## 기타 질문 및 특이 사항
- 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

## POSTMAN을 활용한 로그인 테스트
![스크린샷 2021-09-28 오후 5 55 30](https://user-images.githubusercontent.com/72376931/135056315-1f712af9-ca51-43b6-9d85-b5201e42e572.png)

2021-09-28 10:05 UTC, lordmyshepherd requested changes

2021-09-28 10:05 UTC, lordmyshepherd commented on students/seungjun/users/views.py
> +            input_password = data['password']
변수명은 간결하고 명확하게 선언해주세요. `input_` 과 같은 용어는 불필요합니다~
또한 json.loads() 함수를 호출하는 경우에 decode error가 발생할 수 있으므로 `try`, `except`문 안에 추가해주세요!

```suggestion

        try:
            data      = json.loads(request.body)
            email    = data['email']
            password = data['password']
```

2021-09-28 11:33 UTC, palza4dev commented on students/seungjun/users/views.py
> +            input_password = data['password']
data 변수는 try문 안에서 선언하고, email과 password 변수명 수정하겠습니다

2021-09-28 13:28 UTC, kyeongraekim requested changes
안녕하세요 승준님! 아래 내용 확인해주시고 수정해주세요~

2021-09-28 13:28 UTC, kyeongraekim commented on students/seungjun/users/views.py
> +            if user.password == password:
기능상에서는 문제 없어 보이는 코드이나 가독성 면에서 제한 조건들을 다 통과하고 나면 제일 마지막에 로그인이 성공하게 되는 로직이 가독성과 로직 플로우상 흐름이  좋아 보입니다. 한 번 수정을 고려해보세요!

2021-09-28 13:28 UTC, kyeongraekim commented on students/seungjun/users/views.py
> +            data = json.loads(request.body)
새로 추가 해주신 코드 내용의 변수명 정렬이 조금 아쉽습니다. 간단히 수정해주세요!

2021-09-29 01:04 UTC, palza4dev commented on students/seungjun/users/views.py
> +            data = json.loads(request.body)
다른 변수들과 맞추어 재정렬 했습니다!

2021-09-29 01:07 UTC, palza4dev commented on students/seungjun/users/views.py
> +            if user.password == password:
패스워드가 일치하지 않으면 에러를 반환하도록 수정하고, 로그인 성공 로직은 마지막으로 옮겼습니다

2021-09-29 01:41 UTC, kyeongraekim approved these changes

2021-09-29 01:42 UTC, kyeongraekim commented
LGTM!~ 다음 단계 이어서 진행해주세요~

2021-09-29 01:42 UTC, merged