[구본욱] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/25-westagram-backend pull request #59
Opened 2021-09-28 10:51 UTC by qhsdnr0

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- views, validations, users.urls, westagram.urls 전 내용 추가
- models의 phone_number 수정 (unique=True -> False)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요

- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-28 13:41 UTC, kyeongraekim requested changes
안녕하세요 본욱님 아래 내용에 참고해서 코드 수정해주세요~

2021-09-28 13:41 UTC, kyeongraekim commented on students/bonwook/westagram/users/validations.py
> +    if users_password == None or len(users_password.group()) < 8:
코딩시 보통 상수는 PASSWORD_LENGTH = 8 등으로 명시하며 따로 변수처리를 해줍니다.
제 3자와 협업시 코딩으로 언제든지 기획 변경으로 상수값을 변경할 소요가 생기기 때문입니다.

2021-09-28 13:41 UTC, kyeongraekim commented on students/bonwook/westagram/users/views.py
> +from .validations import *
실제 코드에서는 import시 asterisk 사용을 지양해주세요!

2021-09-28 13:41 UTC, kyeongraekim commented on students/bonwook/westagram/users/views.py
> +class UserView(View):
UserView의 클래스명이 불분명합니다. 정확히 어떤 기능을 하는 View인지 알 수 있게 명칭을 바꾸어 주세요!

2021-09-29 01:38 UTC, qhsdnr0 commented on students/bonwook/westagram/users/validations.py
> +    if users_password == None or len(users_password.group()) < 8:
넵 별도로 변수생성해서 상수처리 하겠습니다~ 리뷰 감사드립니다

2021-09-29 01:38 UTC, qhsdnr0 commented on students/bonwook/westagram/users/views.py
> +from .validations import *
* 대신에 validations에 있는 두 함수명을 따로 적어서 import 했습니다.

2021-09-29 01:40 UTC, qhsdnr0 commented on students/bonwook/westagram/users/views.py
> +class UserView(View):
이건 생각을 못했던 부분이네요.. SignupView로 클래스명 바꾸고
로그인 기능 구현할 때 LoginView로 생성하겠습니다.

2021-09-29 01:43 UTC, kyeongraekim approved these changes

2021-09-29 01:44 UTC, kyeongraekim commented
LGTM!~ 본욱님 다음 내용 이어서 진행해주세요!~

2021-09-29 01:44 UTC, merged