[김민찬] Mission 6: 로그인 JWT 적용
wecode-bootcamp-korea/25-westagram-backend pull request #60
Opened 2021-09-28 10:59 UTC by cozyClassic

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
로그인 시 토큰 부여 구현(JWT)
		 
## 수정 사항들 자세한 내용
- JWT 모듈 import
- 사용자가 비밀번호 입력하는 로그인 시, JSON Response에 JWT토큰을 포함해서 전달함.

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-28 14:09 UTC, kyeongraekim requested changes
안녕하세요 민찬님 몇 가지 수정 사항 반영해서 다시 PR 푸시해주세요~

2021-09-28 14:09 UTC, kyeongraekim commented on students/minchan/westagram/users/views.py
> +        user_id = Users.objects.filter(email=email)[0].id
- 유니크한 이메일 값을 불러오려면 get() 메소드가 더 낫지 않을까요? filter()와 get()의 차이를 생각해보고 수정해주세요~

- 그리고 만일 filter에 대한 사용이 기획상의 의도라면 [0]으로 인덱싱하는 것보다  .first() 메소드를 쓰는 것이 더 효율 적일 수 있습니다. 추후에 의도하신 내용에 대한 간략한 설명 부탁드립니다~

2021-09-28 14:09 UTC, kyeongraekim commented on students/minchan/westagram/users/views.py
>          if not (self.is_user_exist(email) and self.is_pw_match(email,password)):
if not (a and b) 가 if not a or not b 보다 연산이 보다 빠르다는 점을 잘 잡아주셨습니다. 

다만, 이 부분을 보다가 든 생각은 윗 부분에 정의된 현재 코드에서 호출하는 다양한 validation 함수 들을 validators.py의 형태로 따로 만들어서 따로 관리한다면, 각 파일의 성격을 더 잘 띄는 좋은 코딩이 될 것 같습니다.

2021-09-29 09:42 UTC, cozyClassic commented on students/minchan/westagram/users/views.py
> +        user_id = Users.objects.filter(email=email)[0].id
get() 메소드로 변경했습니다.
오류가 발생하는 것에 대한 두려움 때문에 filter를 사용하고 싶었는데,
(오류가 발생하면 어떻게 대처해야할지 코드짜는게 힘겨워서)
그냥 감수해야 하는거라는걸 깨달았습니다.

2021-09-29 09:42 UTC, cozyClassic commented on students/minchan/westagram/users/views.py
>          if not (self.is_user_exist(email) and self.is_pw_match(email,password)):
validation.py 로 파일 분리했습니다!
근데 이름을 잘못지었네요....

2021-09-29 12:11 UTC, kyeongraekim approved these changes

2021-09-29 12:11 UTC, kyeongraekim commented
LGTM!~ 다음 단계 이어서 진행해주세요~

2021-09-29 12:11 UTC, merged