[양가현] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/25-westagram-backend pull request #62
Opened 2021-09-28 15:07 UTC by chrisYang256

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
-ADD: LogIn view
		 
## 수정 사항들 자세한 내용
ADD: Login view at users/views.py
ADD: login url at users/urls.py

## 기타 질문 및 특이 사항
오늘도 럭키한 하루 되시기를 바랍니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-29 01:01 UTC, kyeongraekim requested changes
안녕하세요 가현님~ 아래 내용 확인 후 수정 부탁드려요!
성공적으로 로그인에 성공한 httpie 통신 시험  메세지들도 스크린샷을 찍어서 보내주세요~

2021-09-29 01:01 UTC, kyeongraekim commented on students/gahyun/westagram/users/views.py
> +            # check email
코드 리딩을 통해 충분히 이해가 가능한 주석은 삭제 해주세요~

2021-09-29 01:01 UTC, kyeongraekim commented on students/gahyun/westagram/users/views.py
> +            # check password
이 부분도 불필요해 보입니다~

2021-09-29 01:01 UTC, kyeongraekim commented on students/gahyun/westagram/users/views.py
> +                return JsonResponse({'MESSAGE': 'DON\'T_EXIST_USER'}, status=401)
메세지에 \ 백슬래시가 잘못 들어 간것 같네요 확인 부탁드립니다.

2021-09-29 01:01 UTC, kyeongraekim commented on students/gahyun/westagram/users/views.py
> +            password_check = User.objects.get(email=data['email']).password
뒤에 _check 부분을 삭제해 주시는게 더 좋은 변수명일 될 것 같습니다.
뒤에 나오는 내용이 유저 객체에서 비밀번호를 끌어오는 것이기 때문에 엄밀한 의미에서 _check 의 기능을 수행하고 있지는 않습니다. 로그인을 위한 뷰클래스에서 작성하고 있기 때문에 부연설명을 의도하지 않아도 충분히 코드의 의도가 파악이 됩니다.
추가 사항으로, 바로 직후에 나오는 "if not password_check ==" 구문에서 리딩이 매끄럽지 않을 수 있어요.

2021-09-29 05:13 UTC, chrisYang256 commented on students/gahyun/westagram/users/views.py
> +                return JsonResponse({'MESSAGE': 'DON\'T_EXIST_USER'}, status=401)
백슬레시를 넣어서 DON'T의 홀 따옴표로 인해 문자열이 오류나지 않게 했습니다.

2021-09-30 05:33 UTC, chrisYang256 commented on students/gahyun/westagram/users/views.py
> +            password_check = User.objects.get(email=data['email']).password
저는 변수명을 용도의 의미로 지었는데 그렇게 하면 안되는 것이었군요!
앞으로 담고있는 정보를 나타내는 의미로 작성토록 하겠습니다.
다른 내용도 숙지하겠습니다.
감사드립니다!

2021-09-30 11:01 UTC, kyeongraekim approved these changes

2021-09-30 11:01 UTC, kyeongraekim commented
LGTM!~ 수고하셨습니다 가현님 다음 단계 이어서 진행해주세요~

2021-09-30 11:01 UTC, merged