[김지훈] MIssion 2: 모델링
wecode-bootcamp-korea/25-westagram-backend pull request #66
Opened 2021-09-29 08:46 UTC by kimfa123

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-29 12:14 UTC, kyeongraekim requested changes
지훈님 아래 사항 참고해서 수정해주세요~

2021-09-29 12:14 UTC, kyeongraekim commented on students/jihoon/westagram/users/models.py
> +    contact  = models.CharField(max_length=100, blank=True, default='')
null=True 와 blank=True의 차이를 비교해보시고 완전한 빈값으로 둘 것인지, 빈 스트링으로 둘 것인지 한 번 더 고민해보세요!~

2021-09-29 12:14 UTC, kyeongraekim commented on students/jihoon/westagram/users/models.py
> +    other_info = models.CharField(max_length=100)
기타 정보인데 꼭 들어가야만 하는 값 일까요? 최초 회원가입 및 로그인 후 유저가 변경해야 되는 값으로 기획을 하신거라면 null값을 허용해주면 더 좋아 보일 것 같아요.

2021-09-30 01:24 UTC, kimfa123 commented on students/jihoon/westagram/users/models.py
> +    other_info = models.CharField(max_length=100)
넵 폼에 빈채로 저장 보다 완전히 비워두는것이 나을거 같습니다. 수정하겠습니다 !

2021-09-30 01:56 UTC, kimfa123 reviewed
현재 모델링 이후 작업도 같이 push가 되어서 수정한 부분만 확인 부탁드리겠습니다.

2021-09-30 02:44 UTC, kyeongraekim requested changes
지훈님~ 한 번만 더 수정 부탁드립니다~

2021-09-30 02:44 UTC, kyeongraekim commented on students/jihoon/westagram/users/models.py
> +    other_info  = models.CharField(max_length=100)
other_info 부분이 아직 blank 또는 null 처리가 되어있지 않네요! 아래 null과 blank 관련 잘 정리된 글 공유해드릴게요!~
https://dev.to/anubhavitis/django-null-true-or-blank-true-or-both-30ed

2021-09-30 09:59 UTC, kyeongraekim commented
LGTM!~

2021-09-30 09:59 UTC, kyeongraekim approved these changes

2021-09-30 09:59 UTC, merged