Feature/juhyeong login
wecode-bootcamp-korea/25-westagram-backend pull request #67
Opened 2021-09-29 09:14 UTC by BnDC

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일,  패스워드 없을시 KEY ERROR 반환
- 이메일, 패스워드 충족 되지 않을 시 401 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-29 12:23 UTC, kyeongraekim requested changes
주형님 아래 내용 참고하셔서 코드 수정해주세요~

2021-09-29 12:23 UTC, kyeongraekim commented on students/juhyeong/users/views.py
> +class LoginsView(View):
파이썬 컨베션에 맞게 클래스 명에 쓰인 모든 명사는 복수가 아닌 단수로 만들어주세요!

2021-09-29 12:23 UTC, kyeongraekim commented on students/juhyeong/users/views.py
> +            return JsonResponse({"message": "KEY_ERROR" + " : email"}, status = 400)
메세지형태가 ":" 를  과도 하게 사용하여서 다소 불분명해보입니다. 
{"message": "abcdefg"} 형태로 깔끔하게 수정해주세요~

2021-09-30 00:35 UTC, BnDC commented on students/juhyeong/users/views.py
> +class LoginsView(View):
단수로 수정하겠습니다

2021-09-30 00:35 UTC, BnDC commented on students/juhyeong/users/views.py
> +            return JsonResponse({"message": "KEY_ERROR" + " : email"}, status = 400)
메시지 수정하겠습니다

2021-09-30 01:43 UTC, kyeongraekim approved these changes

2021-09-30 01:44 UTC, kyeongraekim commented
LGTM!~ 다음 과정 계속 진행해주세요~

2021-09-30 01:44 UTC, merged