[구본욱] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/25-westagram-backend pull request #69
Opened 2021-09-29 10:46 UTC by qhsdnr0

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- views - LoginView 작성
- users.urls - path설정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요

- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-29 12:36 UTC, kyeongraekim requested changes
본욱님~ 아래 사항 참고해서 리뷰 반영해주세요!

2021-09-29 12:36 UTC, kyeongraekim commented on students/bonwook/westagram/users/views.py
> +                    'Validation_Error' : '이메일은 @와 .가 포함된 이메일 형식이어야 합니다.'
- JsonResponse message를 통상적인 서버 통신 형식에 맞게 모두 영문으로 작성해보세요!~
또한 실제로 validation_error를 raise 하는 것이 아니고 JsonReponse 이기 때문에 
{"Message" : "validation_error"} 등으로 작성되면 좋을 것 같습니다.

- 해당 에러 메세지들은 프론트단과 백엔드 자체내부에서 확인하는 메세지이기 때문에 마치 사용자에게 친절하게 알려 주듯이 너무 세세할 필요는 없습니다~

2021-09-29 12:36 UTC, kyeongraekim commented on students/bonwook/westagram/users/views.py
> +                    'Validation_Error' : '비밀번호는 8자리 이상으로 숫자, 문자, 특수기호가 하나 이상 포함되어야 합니다.'
이곳 메세지도 영문 작성 및 위 리뷰사항 참고하여 수정 권고드립니다~

2021-09-29 12:36 UTC, kyeongraekim commented on students/bonwook/westagram/users/views.py
> +            if 'email' not in data or 'password' not in data:
아래 except 문으로 처리한 키에러 핸들링과 중복됩니다. 중복을 피해 어떠한 키에러만 남기면 좋을 지 곰곰이 생각해보세요~

2021-09-29 12:36 UTC, kyeongraekim commented on students/bonwook/westagram/users/views.py
> +                return JsonResponse({'message' : '중복된 이메일입니다.'}, status=400)
이곳도 메세지도 동일 합니다~

2021-09-29 12:37 UTC, kyeongraekim commented
또한 컨플릭트도 다음에 올릴 때 해결해주세요!

2021-09-29 23:07 UTC, qhsdnr0 commented on students/bonwook/westagram/users/views.py
> +                    'Validation_Error' : '이메일은 @와 .가 포함된 이메일 형식이어야 합니다.'
넵 간결하게 작성해보겠습니다. 감사합니다

2021-09-29 23:29 UTC, qhsdnr0 commented on students/bonwook/westagram/users/views.py
> +            if 'email' not in data or 'password' not in data:
넵 제가 고민해봤을 땐 이메일만 입력이 되어도 아래 if문 때문에 INVALID_USER 메시지가 리턴될 수 있어서 except keyerror 부분을 지우는 게 맞다고 판단했습니다.

2021-09-30 01:42 UTC, kyeongraekim requested changes
본욱님 아래 내용 확인해주시고 추가 수정 해주세요!

2021-09-30 01:42 UTC, kyeongraekim commented on students/bonwook/westagram/users/views.py
>              if not User.objects.filter(email=data['email']):
if not 으로 조건을 걸지 않고 if 문으로 걸면 if not - else 로 작성된 로직을 더 깔끔하게 if 문 하나로 줄일 수 있을 것 같아 보이네요! 한 번 수정을 고려해보세요~ 
그리고 존재에 대한 참-거짓을 알려주는 .exists() 메소드를 뒷단에 붙여서 더 로직을 명확하게 표현해주세요~

2021-09-30 01:42 UTC, kyeongraekim commented on students/bonwook/westagram/users/views.py
> +            if 'email' not in data or 'password' not in data:
- 만일 위에 키에러를 살리신다면 not A or not B를 드모르간의 법칙을 이용, not (A and B)로 바꾸어 보시는건 어떨까요? 두 방법에 대해 어떤 내용이 코드 진행상 더 좋은 방법인지 한 번 고민해보세요!  수정 이후에 정상 작동 여부까지 확인해보세요~

- 다른 방법으로는, try 문을 사용하는 의도를 적극 이용하는 차원에서 password = data['password], email=data['email']로 선언해서 아예 앞선부터 키에러를 유도하고, except KeyError를 활용하여 코드 라인 훌는 것을 최소화 할 수 있겠네요!

2021-09-30 01:42 UTC, kyeongraekim commented on students/bonwook/westagram/users/views.py
> +            else:
위 내용을 다 훑고 문제 없이 지나온다면 굳이 else 문이 필요 있을까요? 한 번 고민해보세요!

2021-09-30 02:17 UTC, qhsdnr0 commented on students/bonwook/westagram/users/views.py
>              if not User.objects.filter(email=data['email']):
넵 확인해보니 else문이 불필요했네요 exists()메소드는 없어도 동작에 차이가 없어서 안썼었는데 표현이 명확해지는 이유로 사용하는 거였군요! 감사합니다.

2021-09-30 04:16 UTC, qhsdnr0 commented on students/bonwook/westagram/users/views.py
> +            else:
위와 동일하게 if문들로 에러들을 다 확인한 후에는 불필요한 else문 없이 바로 return해주는 게 더 좋을 듯 합니다.

2021-09-30 13:04 UTC, kyeongraekim approved these changes

2021-09-30 13:04 UTC, kyeongraekim commented
수정 내용 잘 확인했습니다!~ 다음 내용 이어서 푸시해주세요~

2021-09-30 13:04 UTC, merged