[이정아] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/25-westagram-backend pull request #70
Opened 2021-09-29 11:03 UTC by wjddk97

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- views.py 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
views.py
 - SignUpView 추가 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-29 12:47 UTC, kyeongraekim requested changes
정아님 아래 내용 리뷰 참고해주시고 수정해주세요!~

2021-09-29 12:47 UTC, kyeongraekim commented on students/junga/westargram/users/views.py
> +            if re.match(r"^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$", data["password"]) == None:
if == None 구조 보다 if not 으로 변경하여 더 직관적인 참 거짓 논리로 코드 로직을 진행하는 것을 추천드려요~

2021-09-29 12:47 UTC, kyeongraekim commented on students/junga/westargram/users/views.py
> +                return JsonResponse({"message": "ERROR_EMAIL_NEED_@AND."}, status=400)
에러 메세지는 사용자에게 전달하는 내용이아닌 프론트와 백간의 통신 내역이기 때문에 너무 자세한 에러메세지를 적어주실 필요는 없습니다. Invalid_Email 이나 Unauthorized_Email 등의 짧은 영문으로도 충분합니다!

2021-09-29 12:47 UTC, kyeongraekim commented on students/junga/westargram/users/views.py
> +                return JsonResponse({"message": "ERROR_REQUIRE_8_LETTER,NUMBER,SPECIAL_SYMBOLS)"}, status=400)
위 리뷰와 동일한 내용입니다.

2021-09-29 12:47 UTC, kyeongraekim commented on students/junga/westargram/users/views.py
> +            return JsonResponse({'message' : 'FALSE'}, status=400)
True의 반대 의미를 가지는 False 보다는 Success의 반대의미를 가지는 Failure, Failed 등의 언어로 변경 부탁드려요~

2021-09-29 12:47 UTC, kyeongraekim commented on students/junga/westargram/westargram/urls.py
> +    path('users/', include('users.urls'))
westargram/urls.py 의  슬래쉬 위치가 뒤가 아닌 앞으로 놓이게끔 수정해주세요~

2021-09-29 12:47 UTC, kyeongraekim commented on students/junga/westargram/users/urls.py
> +    path('', SignUpView.as_view()),
현재 SignUpView를 받는 클래스에 해당되는 url임을 명시해주셔야합니다.
"/signup" 정도의 path를 추가해주시고, settings.py와 동일선상에 있는 urls.py 와 호환이 잘맞고,
런서버 이후 해당 url들로 잘 접속이 되는지 확인해주세요~

2021-09-30 13:10 UTC, kyeongraekim requested changes
정아님 아래 내용 확인하고 수정부탁드려요~

2021-09-30 13:10 UTC, kyeongraekim commented on students/junga/westargram/users/views.py
> +            if (data['email'] == '') or (data['password'] == ''):
소괄호로 감싸주셨는데 코드리딩의 이해 상 굳이 감쌀 필요는 없어보여요~

2021-09-30 13:10 UTC, kyeongraekim commented on students/junga/westargram/users/views.py
> +                return JsonResponse({"message": "INVALID_PASSWORD)"}, status=400)
윗 단 까지의 모든 에러 메세지가 다 400이네요 ㅎㅎ http의 여러가지 상태코드를 확인해보시고 다르게 적용 한 번 해보세요!~

2021-10-01 07:51 UTC, wjddk97 commented on students/junga/westargram/users/views.py
> +                return JsonResponse({"message": "INVALID_PASSWORD)"}, status=400)
수정했습니다~!

2021-10-01 08:50 UTC, kyeongraekim requested changes
정아님 마지막 부분 아래와 같이 수정해주세요~

2021-10-01 08:50 UTC, kyeongraekim commented on students/junga/westargram/users/views.py
> +            if data['email'] == '' or data['password'] == '':
if not data['email'] or data['password'] 로 작성하시는게 키에러를 발생시키는 논리상 더 맞을 것 같아 보여요~ 그 이유를 곰곰이 생각해보세요!

2021-10-01 08:50 UTC, kyeongraekim commented on students/junga/westargram/users/views.py
> +            User.objects.create(
컨벤션에 맞게 가장 긴 변수명 기준으로 한칸을 띄우는 것에 맞추어서 해당 내용을 바르게 정렬해 주세요~

2021-10-01 10:07 UTC, wjddk97 commented on students/junga/westargram/users/views.py
> +            User.objects.create(
수정했습니다~!

2021-10-02 14:45 UTC, kyeongraekim commented
LGTM!~

2021-10-02 14:45 UTC, kyeongraekim approved these changes

2021-10-02 14:45 UTC, merged