[송영록] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/25-westagram-backend pull request #73
Opened 2021-09-30 04:49 UTC by crescentfull

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일, 비밀번호 회원가입시 조건추가
- 실패시 에러 반환
- 성공시 200 success 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-30 13:25 UTC, kyeongraekim requested changes
영록님 아래 내용 확인해서 수정 반영해주세요~

2021-09-30 13:25 UTC, kyeongraekim commented on students/yeongrok/westagram/users/views.py
> +            regex_password = '\S{8,25}'
굉장히 단순한 정규표현식을 사용하여 비밀번호를 걸러주셨네요~
실제 상용하는 서비스처럼 조금 더 추가해보시는 것은 어떨까요?

2021-09-30 13:25 UTC, kyeongraekim commented on students/yeongrok/westagram/users/views.py
> +            if len(data['password']) or not re.match(regex_password, password):
"if len(data['password'])" 이 부분의 코드가 의미가 불분명하네요. 좀 더 구체적으로 수정이 필요해보여요~

2021-09-30 13:25 UTC, kyeongraekim commented on students/yeongrok/westagram/users/views.py
> +                                mobile_num  =   mobile
변수명은 줄임말 없이 원어 그대로를 작성해주세요~

2021-09-30 15:48 UTC, kyeongraekim requested changes

2021-09-30 15:48 UTC, kyeongraekim commented on students/yeongrok/westagram/users/views.py
> +from django.db.models.fields import EmailField
사용하지 않은 import문은 삭제해주세요~

2021-10-03 10:12 UTC, crescentfull commented on students/yeongrok/westagram/users/views.py
> +            regex_password = '\S{8,25}'
넵~!

2021-10-03 10:12 UTC, crescentfull commented on students/yeongrok/westagram/users/views.py
> +            if len(data['password']) or not re.match(regex_password, password):
아  < 8 을 빼먹었네요 ㅠ 넵

2021-10-03 10:12 UTC, crescentfull commented on students/yeongrok/westagram/users/views.py
> +                                mobile_num  =   mobile
넵!

2021-10-03 10:12 UTC, crescentfull commented on students/yeongrok/westagram/users/views.py
> +from django.db.models.fields import EmailField
넵!

2023-05-06 03:15 UTC, closed without merging