[김순태] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/25-westagram-backend pull request #78
Opened 2021-09-30 11:11 UTC by kimfa123

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-30 15:52 UTC, kyeongraekim requested changes
지훈님~ 아래 내용 참고해서 간략히 수정해주세요~

2021-09-30 15:52 UTC, kyeongraekim commented on students/jihoon/westagram/users/views.py
> +
공백 한 칸이 불필요해 보이네요~ 위 라인들의 차이만큼만 띄어주세요~

2021-09-30 15:52 UTC, kyeongraekim commented on students/jihoon/westagram/users/views.py
> +            other_info  = data['other_info']
이곳에서 null 값이 허용된 모델필드에 한해서는 키에러가 나서는 안됩니다. 모델과 잘 비교해보시면서 data['xx'] 구조를 쓸지 아니면 data.get(xx) 구조를 쓸지 잘 고민해보세요~

2021-10-01 01:13 UTC, kyeongraekim commented on students/jihoon/westagram/users/views.py
> +            other_info  = data['other_info']
지훈님~ 위 해당 부분 .get['x'] 의 대괄호가 아닌 소괄호로 씌어주셔야합니다. 
아마 해당 문법으로는 코드가 정상 작동을 하지 않았을 것으로 보이는데 꼭 PR전에 httpie 시험통신을 해보시는 것을 추천드려요!

2021-10-01 04:52 UTC, kimfa123 commented on students/jihoon/westagram/users/views.py
> +            other_info  = data['other_info']
넵 경래님 통신 확인 해보고 수정해서 푸쉬 합니다 감사합니다 !!

2021-10-01 05:03 UTC, kyeongraekim approved these changes

2021-10-01 05:03 UTC, merged

2021-10-01 05:03 UTC, kyeongraekim commented
LGTM!~ 다음 단계 이어서 진행해주세요~